### ISSUE TITLE
CMS: Assign group to posts / tags

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#150]
Add a Group selection dropdown list (similar to the Categories tag list). The Group selection should be above the Category selection. Groups should be filtered to only include groups to which the editor has Assign access.

This should be added to both the Post and Group editors

![telegram-cloud-photo-size-4-5884013172006961378-x](https://github.com/bccsa/luminary/assets/13463323/40d6f98d-389a-4278-8af5-2fff91206a98)

- [x] Add group selector
- [ ] Filter groups show in group selector to only include groups to which the user has "assign" access

**Comment by belljohan3** [comment]
Hi @ivanslabbert ! Please don't forget the sub-tasks of this issue as discussed yesterday. Thanks
