### ISSUE TITLE
CMS: Edit page visual update

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#216]
Finalize draft/publish toggle position:
consider position which is more visible so that you can see at first glance if the content is published or not
A normal toggle is probably not very clear here, so either make it a text toggle or another solution.

Finalize save button visibility / functionality

**Comment by ivanslabbert** [comment]
Up for discussion

**Comment by ivanslabbert** [comment]
@belljohan3 there is no branch linked to this issue, but it is in review. I could also not find a PR for the issue.

**Comment by belljohan3** [comment]
Hey @ivanslabbert ! 
It is now fixed. You can check now

**Comment by belljohan3** [comment]
Hi @ivanslabbert ! 
The description you had in this issue has been done here in this PR #228.
This PR contains only draft/published toogle button changes.

**Comment by laurensgroeneveld** [comment]
As discussed in the standup, we merged this and will take a look at the translation/language switcher in the sidebar in a followup ticket.
