### ISSUE TITLE
APP: Dark / Light mode selection in app

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#218]
![Image](https://github.com/user-attachments/assets/07401670-291c-43fd-8cbc-a5e792896c78)

Add user preference to user profile menu:

- Dark mode
- Light mode
- Auto

**Comment by belljohan3** [comment]
Hi @ivanslabbert ! 
Please i need the others PR to be reviewed before going ahead with this one.

_**Note that there is HomePage that is still failing as we did some changes in the component file.**_

**Comment by ivanslabbert** [comment]
Some info that might help:
https://vueuse.org/core/useDark/
https://cruip.com/implementing-tailwind-css-dark-mode-toggle-with-no-flicker/#dark-mode-implementation-with-vue
