### ISSUE TITLE
CMS: Expiry date shortcut buttons colour issue

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#241]
![Image](https://github.com/bccsa/luminary/assets/13463323/29d7b70c-9e98-4fad-aa39-f17fae609461)

Background colour should be dark when selected.
Look at text editor buttons for selected colour:

![Image](https://github.com/bccsa/luminary/assets/13463323/f926a0e2-b45a-429f-b924-8373f466b205)

 Also check if the white text colour for selected buttons is needed

**Comment by belljohan3** [comment]
The classes that we setted in the LButton component were in conflicts with what we had in EditContentBasic. I think now it is solved
