### ISSUE TITLE
APP: Review dark mode theme

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#243]
- Gather some inspiration from other dark modes: screenshots of pages or elements of other websites that work well, articles about best practices, etc.
- Review all parts of the app in dark mode: does it look good? A common complaint is that the dark mode is too light
- Suggestion Ivan: use `slate` instead of `zinc` for dark mode (but keep zinc for light mode)
- Keep the hierarchy in mind: elements closer to the user (like popups) should still be lighter than elements farther away (currently some popups have a darker background).

**Comment by DirkDevelopmentFreelance** [comment]
I really enjoy the look and feel of linkedIn's darkmode

**Comment by ivanslabbert** [comment]
![Image](https://github.com/user-attachments/assets/87541152-41b3-46be-8668-c8598b0d38ce)

**Comment by laurensgroeneveld** [comment]
![Image](https://github.com/user-attachments/assets/d29e87f7-6687-447d-94b3-d10d2f21c0b3)

**Comment by belljohan3** [comment]
For Profile Menu...
![Image](https://github.com/user-attachments/assets/4ee448cd-44d2-4346-bbe9-c3c7a489b5fc)

**Comment by belljohan3** [comment]
Modal (Theme and Language selection)
![Image](https://github.com/user-attachments/assets/4f21cc30-7354-41a9-8dce-ba3d31ad1504)

**Comment by belljohan3** [comment]
![Image](https://github.com/user-attachments/assets/5be075a7-c4d7-4eb5-9988-d0d1d23702cb)
I made it a bit more darker !

**Comment by ivanslabbert** [comment]
Reopening issue to solve a bug related to this where the menu bar is being hidden on phones
