### ISSUE TITLE
Fix fields initialized with empty string instead of null in seeding docs

### ISSUE THREAD

**Issue by laurensgroeneveld** [bccsa/luminary#295]
By initializing with an empty string we can get strange behaviour like the video field showing without an actual video in it.

Check all fields, but especially these on the `content` docs:
- `audio`
- `video`
- `localisedImage`

**Comment by DirkDevelopmentFreelance** [comment]
I am working on this.

**Comment by belljohan3** [comment]
Hey @laurensgroeneveld !

This is actually works when we create a new post. But on the posts can come from the seeding process. The video input field keeps open.
May be the problem is not in the code ?

**Comment by laurensgroeneveld** [comment]
> This is actually works when we create a new post. But on the posts can come from the seeding process. The video input field keeps open.

Aha, you're right 👍 The seeded docs have `video` initialized with an empty string as opposed to `null`. We probably want to fix that then, but then it's not really an issue otherwise.

**Comment by laurensgroeneveld** [comment]
I have updated the ticket with this information. That makes this a very small fix.

**Comment by belljohan3** [comment]
This is now fixed
