### ISSUE TITLE
CMS, APP, API: Add option to hide publish date

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#297]
In some cases the publish date needs to be hidden in the app on a post / tag. For tags (and future pages) the this should be the default setting. This could be a global setting (added to PostDto which will add it through inheritance to TagDto).

Suggested position of the control is in the Post Settings component under the Pinned toggle button.

**Comment by belljohan3** [comment]
@ivanslabbert can you please explain it more clearly by may be slipting into small tasks ?
