### ISSUE TITLE
API: Changes to content documents are often reverted after saving

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#315]
The API sometimes / often backdates changes to the previous version of the content document.
This is probably happening when changes to posts/tags are causing an update to the content documents (replicating fields from the post / tag to the content documents), and arriving out of sequence at the client.

**Comment by belljohan3** [comment]
@ivanslabbert I want to take this one, but how can i reproduce this ?

**Comment by oslabbie** [comment]
#217 should be fixed by this, but I need to test if this issue is solved
