### ISSUE TITLE
App: Topic Explorer

### ISSUE THREAD

**Issue by laurensgroeneveld** [bccsa/luminary#320]
- [x] Create a topic explorer that lists topics alphabetically.
- [x] Topics which belongs to a pinned category can be shown at the top as "Featured" (but the featured topics does **not** need to be hidden in the alphabetical list below).
- [x] TBC: The topic names can perhaps be overlayed over the image tiles (will need to add support for that in the still to be created LImage component), with the image blurred so that it is easy to read the text
- [x] Need to determine the image aspect ratio for the topic tiles. (For video we use the video aspect ratio and for audio we will use square. Perhaps a 4:3 aspect ratio could work for topics?)
- [x] Create navigation buttons for the different experiences (separate task?) Can be sticky at bottom of page for mobile view, and perhaps in top bar for PC view. Topic explorer could be named "Explore" in the menu. Video experience could perhaps be "Watch" and future audio experience "Listen".

Idea for layout of Explore page (up for discussion)
![Image](https://github.com/user-attachments/assets/4f8024bf-4aab-4c52-a92a-5fccb4d6c0a2)

**Comment by belljohan3** [comment]
- [ ] Create a category Featured that is pinned
- [ ] Add a french Translation for that Category (En Vedette)
- [ ] Tag some posts with Feature

**Comment by belljohan3** [comment]
- [ ] Create a category Featured that is pinned
- [ ] Add a french Translation for that Category (En Vedette)
- [ ] Tag some posts with Feature

**Comment by belljohan3** [comment]
- [ ] Swap image and text
- [ ] Not use the card view for 
- [ ] Heading is too big and bold
- [ ] Button to swicth feels too heavy, too dark
- [ ]
