### ISSUE TITLE
CMS & APP: Embedded links in text editor

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#333]
- [x] Add automatic conversion of links to anchor tags (`<a></a>`)

## Technical notes

Look up the Link extension which does what we want: https://tiptap.dev/docs/editor/extensions/marks/link#page-title

**Comment by belljohan3** [comment]
Hey @ivanslabbert @DirkDevelopmentFreelance 
The new package installed (`@tiptap/extension-link`) from Tiptap make most of test failing. We need to find a way to fix that. Mostly the tests where we are expecting datas to be rendered. Also, swichting back on the `main` branch keeps the tests failing as well.
