### ISSUE TITLE
CMS: Add test to test language switching on the Post overview.

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#356]
Switching languages should produce the same list as shown with the previous language without giving errors in the console.

**Comment by DirkDevelopmentFreelance** [comment]
On a meeting with @belljohan3 on 30 September, we realised that the list won't always be the same, as we realised that there could be translations for english, but then if you switch over to swahili or chichewa for example, the list is empty. As they have not been translated yet. So the way we wanted to implement the test won't work. I will do some research on what could be a good way to test the filters when a language changes.
