### ISSUE TITLE
APP: Post's without images does not display

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#375]
![Image](https://github.com/user-attachments/assets/8302a155-4cad-419d-a9a0-69aabe51f19d)

See image if no post has a image then it does not display anything 
This is on the main branch, not sure hot it is on production 

Also, the backup image only works if there is an image currently uploaded, if there is not image, the post does not show

**Comment by ivanslabbert** [comment]
Check if not fixed already

**Comment by DirkDevelopmentFreelance** [comment]
When there is no image it shows in homepage with the placeholder image, but it doesn't show in the categories:
Image
Image
