### ISSUE TITLE
API: Check that groups are only synced to CMS clients and not to APP clients

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#386]
Since the app does not have a group editor nor needs to assign groups, group documents should not be synced to the app. This might already be implemented, but check if it really is working as such

**Comment by ivanslabbert** [comment]
Confirmed that group documents currently are (incorrectly) synced to app clients.

**Comment by belljohan3** [comment]
After investigation, it seems like it is already implemented. Check this part in `socketio.ts` from the `api` folder.

`appDocTypes: Array<DocType> = [DocType.Post, DocType.Tag, DocType.Content, DocType.Language];
    cmsDocTypes: Array<DocType> = [DocType.Group, DocType.Change];`
    
    `if (reqData.cms) {
    socket.join(`cms-${docType}-${group}`);
}`
